### PR TITLE
Select a country via its alt names

### PR DESCRIPTION
**Pull request by arslanhashmi**
This adds flexibility to select a country via one of its alt names.
```python
# Example
country = CountryInfo('US')
country.info()
```

### CODE REVIEW

**Comment by arslanhashmi** [comment]
@kaspersorensen @porimol please have a look.

**Comment by arslanhashmi** [comment]
@porimol may you please have a look? I need to add it in my project dependencies..

**Comment by porimol** [comment]
@arslanhashmi you'll get update ASAP!

**Comment by arslanhashmi** [comment]
@porimol can this be merged?

**Pull request merged**
